### ISSUE TITLE
smtp on HestiaCP not worked

### ISSUE THREAD

**Issue by TOWUK** [pachno/pachno#10]
i create account mail on my domain and use smtp on pachno. smtp sent and dont delivery...

**Comment by mzch** [comment]
I tried to set up my SMTP server, but I was unable to select `CONNECTION ENCRYPTION`.
`Use SSL encryption` and `Use TLS encryption` options are gray-outed.
So Pachno failed to send mails.

**Comment by jagansankara** [comment]
Any update on this bug. Because of this, can't able to create users as well.

**Comment by zegenie** [comment]
This was caused by an error in the module initialization so it wasn't able to detect available encryption options. This has been fixed now.
