### ISSUE TITLE
php 7.4 required, can it work with 8.0?

### ISSUE THREAD

**Issue by Krillianaire** [pachno/pachno#13]
Hi,

Any chance of getting instructions on how to get it to work with php8?

 Problem 1
    - Root composer.json requires php ^7.4 but your php version (8.0.12) does not satisfy that requirement.

**Comment by zegenie** [comment]
Yes, pachno should be php 8.0 compatible. Temporarily updating the `composer.json` file with the correct version should allow you to proceed, and we'll update it in the next release too.

**Comment by zegenie** [comment]
Fixed in master, will be available in the next release.
