### ISSUE TITLE
Board not containing tasks created

### ISSUE THREAD

**Issue by superseby2** [pachno/pachno#14]
When creating a task (or idea or ticket),  it does not appear in the board. 

It does appear in the global dashboard though. 

This in the debug console : 

fetch.js:253 Trying to update element [object Object] but it does not exist in markup [error]
fetch.js:254 {form: "report_issue_form", method: "POST", success: {…}}

So the issue is created successfully, but does not appear in the column where created. 

Version . 1.0.2

**Comment by zegenie** [comment]
This is related to issue #11 - please see updates there.
