### ISSUE TITLE
Clicking upload file in a document does not trigger anything

### ISSUE THREAD

**Issue by superseby2** [pachno/pachno#15]
Nothing is happening. Not even a single log.

**Comment by zegenie** [comment]
Thanks. There was a check in place to prevent this, but unfortunately the logic was a bit flawed. Moved this around a bit so now you should be prevented from getting confused if uploads aren't enabled yet.

**Comment by cheuklam** [comment]
Got a weird things when I try to upload when create issue.
It report "Something went wrong when uploading the image XXXXXX" when I try to drag a file into the issue reporting form, but it actually uploaded to the file folder and the json returned the uploaded URL in JSON. It has no problem when uploading file after the "issue" is created.

Also, no matter enabled upload in project setting or not, there is no problem in uploading file, not a big issue though.

**Comment by zegenie** [comment]
@cheuklam could you report this as a separate issue?
