### ISSUE TITLE
Module Configuration - Link broke & throws error

### ISSUE THREAD

**Issue by jagansankara** [pachno/pachno#20]
When click on Configuration -> Module, link broke & throw unknown directory error.

The following error occurred:
opendir(/var/www/html/modules/): failed to open dir: No such file or directory
The following error occured:
opendir(/var/www/html/modules/): failed to open dir: No such file or directory in /var/www/html/core/framework/Context.php, line 1013

**Comment by zegenie** [comment]
Is this from a fresh install? What is the configuration setup here?

**Comment by jagansankara** [comment]
This is fresh setup. And sorry, since application is throwing error in module, user creation and mail configuration, I've removed it. But, I remember that all the configuration I used are default.

**Comment by zegenie** [comment]
Thanks for taking the time to report the issue. It seems like the downloadable archive doesn't include the empty `modules/` folder, causing this error. The fix would be to simply create the folder and try again, but without prior knowledge that's hard to find out.

I've pushed a fix for this which will be available in the next release, or in `master` for anyone downloading directly from there.
