### ISSUE TITLE
Cannot forget password or edit user password

### ISSUE THREAD

**Issue by cheuklam** [pachno/pachno#24]
Hi,

I am testing over pachno in use self-hosting environment, and is following the installation procedure to install for a few times.

However, not sure why everything works well besides user password changing, the API will return {"error":"Please log in to continue"}
Same thing heppans on forget password. I already configured the SMTP server so that the forget password button appears, but when I click the button, the javascript console shows "cannot call to undefined /Users" 

I think the whole pachno program is great, I would dare to said it is currently the best opensource bug tracking platform so far. But these little issue really keeping me off .... hope it can be fixed real soon.

Best regards,
CL

**Comment by cheuklam** [comment]
OS: CentOS 7
Webserver: Apache 2.4
PHP: 7.4

**Comment by zegenie** [comment]
Thanks for taking the time to report - will look into this asap

**Comment by zegenie** [comment]
Unfortunately, this functionality had not yet been ported to Pachno. It has been restored now and will be available in the next release or directly from `master` if you're updating from there.
