### ISSUE TITLE
Cannot set client for project

### ISSUE THREAD

**Issue by cheuklam** [pachno/pachno#25]
One more issue is noticed.

When I choose the project and wanna pick a client, nothing happened.
Neither any js function (nothing show in console)
nor any AJAX request fired (nothing shown in fiddler)

**Comment by zegenie** [comment]
This is supposed to be an auto-updating dropdown, but it was missing the form wrapper. A fix has been pushed that will be available in the next release.

If you're able to update from the latest `master`, the fix is available already.
