### ISSUE TITLE
In a new document (documentation), adding an image does not work

### ISSUE THREAD

**Issue by superseby2** [pachno/pachno#27]
Here what is found in the window debugger.

8000/files/show/4:1 GET https://pachno.afreelancersworld.com:8000/files/show/4 net::ERR_CONNECTION_TIMED_OUT
Image (async)
g @ bundle.js:1
value @ bundle.js:1
set @ bundle.js:32
value @ bundle.js:32
onUpload @ bundle.js:32
(anonymous) @ bundle.js:1
Promise.then (async)
value @ bundle.js:1
onSelectFile @ bundle.js:32
(anonymous) @ bundle.js:1
value @ bundle.js:32
value @ editor.js:2
value @ editor.js:2
value @ editor.js:2
(anonymous) @ editor.js:2

- Uploads are allowed in settings / 
- Using Send-x or not does not make any difference

Pachno is behind nginx which does a basic proxy-pass

**Comment by zegenie** [comment]
What happens if you try to open the file directly in the browser - does it still time out?

This seems like an nginx configuration issue, but it's hard to tell without looking into it.
