### ISSUE TITLE
Changing password from someone invited to join a project is failing

### ISSUE THREAD

**Issue by superseby2** [pachno/pachno#28]
The error is 
https://xxx.com/account/change/password/a9e1575c-d925-4616-b8ac-971b0cb1c47a 403 (Forbidden)
(anonymous) @ fetch.js:168
fetchHelper @ fetch.js:97
formSubmitHelper @ fetch.js:368
submitForm @ ui.js:321
autoSubmitForm @ ui.js:290
dispatch @ jquery.js:5430
elemData.handle @ jquery.js:5234

![image](https://user-images.githubusercontent.com/32198925/152579898-618c7c20-f9a1-42cc-9256-f687ee844d03.png)

**Comment by zegenie** [comment]
This seems like an issue with the CSRF token used in the password change dialog. Will have a look.
