### ISSUE TITLE
CSS broken in Documentation

### ISSUE THREAD

**Issue by Gurkengewuerz** [pachno/pachno#33]
Hey,

first of all i've found this wonderful project while searching for some kind of JIRA alternatives. This projects look sooo great! Please keep going.

I was wondering if you already noticed the jumping and broken CSS on the documentation page? The documentation page is a great feature but not really useful in this state.

https://user-images.githubusercontent.com/10966337/162855944-2f742fbc-b650-4029-ba6c-53e61f294b01.mp4

btw. i would really love to see the possibility to disable account creation 👀

Greetings from Germany

**Comment by ElyFura** [comment]
Same Issue here wanted to test Pachno for my Team and the Documentation Pages jumping arround like that all the time

**Comment by rafaelsabino** [comment]
Same error here :/

**Comment by rafaelsabino** [comment]
Hi, for anyone who wants to solve this error, I was able to just remove two duplicate styles that overshadow the main style in the page execution. As the loading was done dynamically along with the images and elements, it happens that the calculation of the height and width of the page were broken. With that, just remove or comment two lines from the theme file located at lines 7979 and 7984 at:

./pachno/themes/oxygen/css/theme.css

![image](https://user-images.githubusercontent.com/12975702/172037130-72cc0ea6-91d8-4c8d-b7f9-e41af88cab67.png)

Código final:
`.content-with-sidebar {
  display: flex;
  flex-direction: row;
  flex: 1 1 100%;
  height: 100%;
  padding: 0;
  margin: 0;
  box-sizing: border-box;
  overflow: hidden;
  position: relative; }
  .content-with-sidebar > div:not(.sidebar):not(.fixed-position) {
    /* height: 100%; */
    box-sizing: border-box;
    overflow: auto;
    flex: 1 1 auto;
    background-color: rgba(225, 225, 225, 0.15);
    /* display: flex; */
    flex-direction: column;
    align-content: flex-start;
    align-items: flex-start;
    justify-content: flex-start; }
    .content-with-sidebar > div:not(.sidebar):not(.fixed-position).hidden {
      display: none; }`

-------------
Result:
![image](https://user-images.githubusercontent.com/12975702/172037268-c1aaa8c1-9a8f-48d6-b7b3-08f49f0d47c4.png)

**Comment by zegenie** [comment]
I can't reproduce this issue in firefox - which browser are you using ?

**Comment by zegenie** [comment]
All Chrome-based, so they will all have the same issues. Seems like this is an issue with the simplebar wrapper and the way chrome handles changes in the layout. Will release a hotfix for this issue later today.
