### ISSUE TITLE
Usergroups not saving

### ISSUE THREAD

**Issue by NiemandNatural** [pachno/pachno#35]
Sers!
When I set a users usergroup to "Admin", click "Save" and then reopen the user profile, it's back to "Regular User".
Users can sign up and Team memberships seem to be saved, so I guess it's not a DB issue.
It also gives a little success notification on the bottom - but even after a npm cache clear, a relog and a browser cache clear the user group stays the same.

I installed it twice now.

(System: Ubuntu upgraded to 20.04; apache2; npm/composer rather up2date; php8.0.*; mariaDB/MySQL)

**Comment by zegenie** [comment]
Thanks for reporting! This will be fixed in the next release.
