### ISSUE TITLE
Help for translation into Chinese Traditional / Simplified

### ISSUE THREAD

**Issue by cheuklam** [pachno/pachno#47]
Hi, I can help translating pachno into chinese version, can I have an excel / spreadsheet or something for the required translation files?

**Comment by zegenie** [comment]
We use transifex to translate pachno: https://www.transifex.com/pachno/pachno/

**Comment by cheuklam** [comment]
great, will help on translating

**Comment by cheuklam** [comment]
Basically gone through all the chinese translation once. There is still some translation text I am not sure where it will be shown so the translation might not be 100% accurate. Will keep update when it is included in next release!

**Comment by zegenie** [comment]
Looks good - we'll include it in the next release and you can check it out then

**Comment by cheuklam** [comment]
Seems there is still some translation is a bit weird in the chinese context. I will keep update transifex, please do incorporate the latest update in next release, thanks.

One more notes is that .... the translation is "Chinese (Traditional)" not simplified, I input into simplified only becoz there is no "traditional" option...
