### ISSUE TITLE
Class "pachno\core\modules\configuration\Datatype" not found

### ISSUE THREAD

**Issue by flyingfishzxf** [pachno/pachno#65]
**Version**: 1.0.6
**Page**: Configure issue fields
**action**: Click the arrow-right icon
**result**: get the error as the title
![image](https://user-images.githubusercontent.com/8775528/236200866-7dda6554-a743-40b9-a435-e19be1d51f13.png)

**Resolve**:
add `use pachno\core\entities\DataType;` in `core/modules/configuration/Components.php`

**Comment by zegenie** [comment]
Thanks for reporting the issue. Pushed a fix to `master` now, will be part of the next release.
