### ISSUE TITLE
Install error - ScopedTable::setup should be compatible with b2db\Table::setup

### ISSUE THREAD

**Issue by Britford** [pachno/pachno#9]
Environment:
Pachno 1.0.1, Debian 10.9,  PHP 7.4, MariaDB 15.1

Composer installed ok except 3 phpunit abandoned warnings (php-token-stream, phpunit-mock-objects, phpunit-skeleton-generator)
Browse to site to finish installation, after entering DB info, press "Continue", the following error displays:

```
The following error occured:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column) in /var/www/pachno/core/entities/tables/ScopedTable.php, line 99
```

**Comment by cerelli** [comment]
Environment:
Pachno 1.0.1, Windows

`The following error occurred:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column)
The following error occured:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column) in C:\TuttoQui\laragon\www\pachno\core\entities\tables\ScopedTable.php, line 99`

**Comment by emmesscee** [comment]
same here

`The following error occurred:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column)
The following error occured:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column) `

**Comment by Britford** [comment]
Issue confirmed in 1.0.2 as well.

```
Creating tables ...
PHP Notice:  Undefined index: HTTP_ACCEPT in /var/www/pachno/core/framework/Request.php on line 567
The following error occured:

Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column)
occured in
/var/www/pachno/core/entities/tables/ScopedTable.php, line 99
```

**Comment by dphillips479** [comment]
Environment:
Pachno 1.0.2, PHP 7.4, MariaDB Ver 15.1, Linux 4.9.0-16-amd64 Debian

Same error message when installing on webhosting.
Installation on a Laravel Homestead Box VM has problems.

**Comment by 1-0-1developer** [comment]
Same problem here, version 1.02, 
after composer update and pointing webbrowser to the pachno url I get the error

`The following error occurred:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column)
The following error occured:
Declaration of pachno\core\entities\tables\ScopedTable::setup(string $b2db_name, string $id_column): void should be compatible with b2db\Table::setup($b2db_name, $id_column) in D:\pachno\core\entities\tables\ScopedTable.php, line 99`

**Comment by zegenie** [comment]
Closing this issue since this has been fixed.

**Comment by dphillips479** [comment]
Since I'm not the only one who's had this problem, maybe mentioning the required PHP packages would be nice. Sometimes logs seem only like a mess of random letters, but I would probably have stumbled over the system requirements and think, 'well maybe...'

Asked the hoster if there was any chance of getting ext-apcu installed. Direct answer was: no chance.
Set up pachno on my vserver again without any problems. So not having the requirement for apcu (if possible)  would be really nice too. I actually like this thing.

**Comment by zegenie** [comment]
I'm sorry if I misunderstood the issue here, but I'd very much like to know how, specifically, we can improve this if it isn't fixed yet.

**Comment by zegenie** [comment]
After working on this issue over the weekend, I've pushed an update that should hopefully fix the issue described above, and also removes the dependency on the apcu extension. This should solve the issue, but let me know if it doesn't.

**Comment by zegenie** [comment]
I'm closing this issue as resolved now, but if it hasn't been resolved, please post a comment and I'll revisit it.
